name: Release - build windows EXE and create GitHub Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-release-windows:
    name: Build & Release (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # change to your target SDK

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish single-file self-contained exe (x64)
        run: |
          dotnet publish src/ProtonVpn.App/ProtonVpn.App.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=false -p:PublishReadyToRun=true --self-contained true -o artifacts/win-x64
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: List artifacts (debug)
        run: dir artifacts\win-x64

      - name: Optional: Decode signing PFX (if secret present)
        if: ${{ secrets.SIGNING_PFX != '' }}
        shell: pwsh
        env:
          SIGNING_PFX: ${{ secrets.SIGNING_PFX }}
        run: |
          Write-Host "Decoding SIGNING_PFX..."
          $pfxBase64 = $env:SIGNING_PFX
          if ([string]::IsNullOrEmpty($pfxBase64)) {
            Write-Host "SIGNING_PFX is empty; skipping."
            exit 0
          }
          $pfxBytes = [System.Convert]::FromBase64String($pfxBase64)
          $outPath = Join-Path $env:GITHUB_WORKSPACE 'signing.pfx'
          [System.IO.File]::WriteAllBytes($outPath, $pfxBytes)
          Write-Host "PFX written to $outPath"

      - name: Optional: Sign exe with signtool
        if: ${{ secrets.SIGNING_PFX != '' }}
        shell: pwsh
        env:
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          $exe = Get-ChildItem -Path artifacts\win-x64 -Filter *.exe | Select-Object -First 1
          if ($null -eq $exe) {
            Write-Error "No exe found to sign"
            exit 1
          }
          $pfxPath = Join-Path $env:GITHUB_WORKSPACE 'signing.pfx'
          if (-not (Test-Path $pfxPath)) {
            Write-Error "PFX not found at $pfxPath"
            exit 1
          }
          $pfxPassword = $env:SIGNING_PASSWORD
          Write-Host "Signing $($exe.FullName)..."
          & "C:\Program Files (x86)\Windows Kits\10\bin\x64\signtool.exe" sign /fd SHA256 /a /f $pfxPath /p $pfxPassword /tr http://timestamp.digicert.com /td SHA256 $exe.FullName

      - name: Create ZIP artifact
        shell: pwsh
        env:
          ZIP_NAME: artifacts/ProtonVpn-windows-x64-${{ github.ref_name }}.zip
        run: |
          $zip = $env:ZIP_NAME
          if (Test-Path $zip) { Remove-Item $zip -Force }
          Compress-Archive -Path artifacts\win-x64\* -DestinationPath $zip
          Write-Host "ZIP created: $zip"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Release built by GitHub Actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "artifacts/ProtonVpn-windows-x64-${{ github.ref_name }}.zip"
          asset_name: "ProtonVpn-windows-x64-${{ github.ref_name }}.zip"
          asset_content_type: application/zip
